spring:
    jpa:
      generate-ddl: false
      hibernate:
        ddl-auto: validate
      database: MYSQL
      show-sql: true
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://5959efdf13c1d.gz.cdb.myqcloud.com:10104/aep_service?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: cdb_outerroot
      password: 7OL$5pb5hJ3
    resources:
      cache-period: 1
      chain:
        cache: false
    http:
      multipart:
        enabled: true
        max-file-size: 20MB
        max-request-size: 20MB
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      pool:
        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8       # 连接池中的最大空闲连接
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0       # 连接池中的最小空闲连接
      timeout: 0        # 连接超时时间（毫秒）

logging:
  path: /data/logs/wechat

server:
  port: 8080





